model_opts:
  name: "attention_unet_seg"
  args:
    inchannels: 1
    outchannels: 1
    # The net_depth will change accordingly to the patch size. For 128x128 it is 3, for 256x256 it is 4. This will define the number of layers of the architecture.
    net_depth: 4

train_par:
  gpu_to_use: "cuda:0" # 'cuda:1', select the GPU where you want your training. if 'default' it will use torch.device("cuda" if torch.cuda.is_available() else "cpu")
  random_seed: "default" # set to 'default' to replicate MICCAI's results
  epochs: 90
  batch_size: 3
  workers: 8
  lr: 0.001
  weight_decay: 0.001
  eval_threshold: 0.5
  patience: 30
  early_stopping_flag: True
  results_path: "/media/stefano/Seagate Expansion Drive/rochester_luis_emilio/LIMICM2_emilio/giancarlo_model/Classification/results_seg/experiment/Tesis_kfold_10_new_data_new_loss_less_patient"
  optimizer:
    name: "AdamW"
  loss_opts:
    name: "TopologicalPoolingLoss" # BCELoss ; SigmoidFocalLoss; TopologicalPoolingLoss; BCEDiceLoss
    args:
      weight: 0.5 # this is for BCELogits (value will be computed automatically) & BCEDiceLoss (you need to input a value, default: 0.1)
      alpha: 1 # this is only for focal loss
      gamma: 2 # this is only for focal loss
  num_classes: 2

dataset:
  experiment: "experiment"
  data_dir: "/media/stefano/Seagate Expansion Drive/rochester_luis_emilio/LIMICM2_emilio/giancarlo_model/prueba/3D_fold"
  train: "/media/stefano/Seagate Expansion Drive/rochester_luis_emilio/LIMICM2_emilio/giancarlo_model/Classification/data_csv_seg/data_20%/data_train_seg_20%.csv"
  dev: "/media/stefano/Seagate Expansion Drive/rochester_luis_emilio/LIMICM2_emilio/giancarlo_model/Classification/data_csv_seg/data_20%/data_test_seg_20%.csv"
  test: "/media/stefano/Seagate Expansion Drive/rochester_luis_emilio/LIMICM2_emilio/giancarlo_model/Classification/data_csv_seg/data_20%/data_test_seg_20%.csv"
  cache_data: False
  rescale_factor: 128
